package sdk

import (
	"context"
	"errors"
	"strings"
	"time"
)

type KeyedProvider interface { Provider; WithAPIKey(string) Provider }
type RouterClient struct { Router *Router; Adapters map[AdapterID]Provider; Retry RetryPolicy }
func NewRouterClient(router *Router) *RouterClient { return &RouterClient{Router: router, Adapters: make(map[AdapterID]Provider), Retry: DefaultRetryPolicy()} }
func (c *RouterClient) RegisterAdapter(id AdapterID, p Provider) { c.Adapters[id] = p }
func (c *RouterClient) providerFor(session *Session, model string) (Provider, ModelRoute, error) {
	route, err := c.Router.Resolve(session.config.Provider, model)
	if err != nil && strings.Contains(err.Error(), "model catalogue for provider=") {
		provider := session.config.Provider
		adapterConfig, configErr := c.Router.Provider(provider)
		if configErr == nil { if _, ok := c.Adapters[adapterConfig.Adapter]; ok { if refreshErr := c.RefreshModels(context.Background(), provider); refreshErr == nil { route, err = c.Router.Resolve(provider, model) } else { err = refreshErr } } }
	}
	if err != nil { return nil, ModelRoute{}, err }
	p, ok := c.Adapters[route.Adapter]; if !ok { return nil, ModelRoute{}, &RouteError{Provider: route.Provider, Model: route.Model, Adapter: route.Adapter} }
	if kp, ok := p.(KeyedProvider); ok { key, err := session.APIKey(); if err != nil { return nil, ModelRoute{}, err }; p = kp.WithAPIKey(key) }
	if config, err := c.Router.Provider(route.Provider); err == nil && config.BaseURL != "" { if ep, ok := p.(EndpointProvider); ok { p = ep.WithBaseURL(config.BaseURL) } }
	return p, route, nil
}
type RouteError struct { Provider ProviderID; Model string; Adapter AdapterID }
func (e *RouteError) Error() string { return "sdk: adapter not registered for provider=" + string(e.Provider) + " model=" + e.Model + " adapter=" + string(e.Adapter) }
func (c *RouterClient) RefreshModels(ctx context.Context, provider ProviderID) error { config, err := c.Router.Provider(provider); if err != nil { return err }; adapter, ok := c.Adapters[config.Adapter]; if !ok { return &RouteError{Provider: provider, Adapter: config.Adapter} }; policy := c.Retry; if policy.MaxAttempts <= 0 { policy.MaxAttempts = 1 }; var last error; for attempt := 1; attempt <= policy.MaxAttempts; attempt++ { err = c.Router.RefreshModels(ctx, provider, adapter); if err == nil { return nil }; last = err; if attempt == policy.MaxAttempts || !retryable(err) { break }; if err := sleepBackoff(ctx, policy, attempt); err != nil { return err } }; return last }
func (c *RouterClient) Generate(ctx context.Context, session *Session, req Request) (Response, error) { cfg := session.Config(); model := req.Model; if model == "" { model = cfg.Model }; p, route, err := c.providerFor(session, model); if err != nil { return Response{}, err }; req.Provider, req.Model = route.Provider, route.Model; if len(req.Messages) == 0 { req.Messages = session.History() }; if req.ThinkingLevel == "" { req.ThinkingLevel = cfg.ThinkingLevel }; if req.Temperature == nil && cfg.Temperature != nil { v := *cfg.Temperature; req.Temperature = &v }; resp, err := c.generateRetry(ctx, session, p, req); if err != nil { session.RepairHistory(); return Response{}, err }; resp.Provider, resp.Model = string(route.Provider), route.Model; return resp, nil }
func (c *RouterClient) generateRetry(ctx context.Context, session *Session, p Provider, req Request) (Response, error) { policy := c.Retry; if policy.MaxAttempts <= 0 { policy.MaxAttempts = 1 }; if policy.InitialBackoff <= 0 { policy.InitialBackoff = time.Millisecond }; if policy.MaxBackoff <= 0 { policy.MaxBackoff = policy.InitialBackoff }; var last error; for attempt := 1; attempt <= policy.MaxAttempts; attempt++ { requestID, recordErr := session.RecordRequest(attempt, req); if recordErr != nil { return Response{}, recordErr }; resp, err := p.Generate(ctx, req); resp.Provider, resp.Model = string(req.Provider), req.Model; if err == nil { if recordErr := session.RecordResponse(requestID, resp, nil); recordErr != nil { return Response{}, recordErr }; return resp, nil }; last = err; if recordErr := session.RecordResponse(requestID, resp, err); recordErr != nil { return Response{}, recordErr }; if attempt == policy.MaxAttempts || !retryable(err) { break }; if err := sleepBackoff(ctx, policy, attempt); err != nil { return Response{}, err } }; return Response{}, last }
func retryable(err error) bool { if err == nil || errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) { return false }; var statusErr HTTPStatusError; if errors.As(err, &statusErr) { return RetryableHTTPStatus(statusErr.HTTPStatusCode()) }; return true }
func sleepBackoff(ctx context.Context, p RetryPolicy, attempt int) error { d := p.InitialBackoff; for i := 1; i < attempt; i++ { if d >= p.MaxBackoff/2 { d = p.MaxBackoff; break }; d *= 2 }; if d > p.MaxBackoff { d = p.MaxBackoff }; t := time.NewTimer(d); defer t.Stop(); select { case <-ctx.Done(): return ctx.Err(); case <-t.C: return nil } }
func (c *RouterClient) GenerateTurn(ctx context.Context, session *Session, user Turn, req Request) (Response, error) { before := session.History(); session.Append(user); req.Messages = session.History(); resp, err := c.Generate(ctx, session, req); if err != nil { session.ReplaceHistory(before); return Response{}, err }; commitResponse(session, resp); return resp, nil }
func commitResponse(session *Session, resp Response) { if len(resp.Content) > 0 || resp.Reasoning != nil { turn:=Turn{Role:RoleModel,Content:append([]ContentPart(nil),resp.Content...)}; if resp.Reasoning!=nil { r:=*resp.Reasoning; turn.Reasoning=&r }; session.Append(turn) }; for _, call := range resp.ToolCalls { call := call; session.Append(Turn{Role: RoleToolCall, ToolCall: &call}) } }
func (c *RouterClient) Stream(ctx context.Context, session *Session, req Request) (<-chan Event, error) { cfg := session.Config(); model := req.Model; if model == "" { model = cfg.Model }; p, route, err := c.providerFor(session, model); if err != nil { return nil, err }; req.Provider, req.Model = route.Provider, route.Model; if len(req.Messages) == 0 { req.Messages = session.History() }; if req.ThinkingLevel == "" { req.ThinkingLevel = cfg.ThinkingLevel }; if req.Temperature == nil && cfg.Temperature != nil { v := *cfg.Temperature; req.Temperature = &v }; return c.streamRetry(ctx, session, p, req) }
func (c *RouterClient) streamRetry(ctx context.Context, session *Session, p Provider, req Request) (<-chan Event, error) { policy := c.Retry; if policy.MaxAttempts <= 0 { policy.MaxAttempts = 1 }; out := make(chan Event, 16); go func() { defer close(out); for attempt := 1; attempt <= policy.MaxAttempts; attempt++ { requestID, recordErr := session.RecordRequest(attempt, req); if recordErr != nil { out <- Event{Type: EventError, Err: recordErr}; return }; ch, err := p.Stream(ctx, req); if err != nil { resp := Response{Provider: string(req.Provider), Model: req.Model}; _ = session.RecordResponse(requestID, resp, err); if attempt < policy.MaxAttempts && retryable(err) { if err := sleepBackoff(ctx, policy, attempt); err == nil { continue } else { out <- Event{Type: EventError, Err: err}; return } }; out <- Event{Type: EventError, Err: err}; return }; started := false; var streamErr error; var text []ContentPart; var calls []ToolCall; var reasoning *ReasoningState; var finalResp *Response; for ev := range ch { if ev.Type == EventError { streamErr = ev.Err; break }; started = true; if ev.Type == EventText && ev.Text != "" { text = append(text, ContentPart{Type: ContentText, Text: ev.Text}) }; if ev.Type == EventReasoning && ev.Reasoning != nil { r := *ev.Reasoning; if reasoning == nil { reasoning = &ReasoningState{} }; if r.ID != "" { reasoning.ID = r.ID }; reasoning.Text += r.Text }; if ev.Type == EventToolCall && ev.ToolCall != nil { calls = append(calls, *ev.ToolCall) }; if ev.Type == EventDone && ev.Response != nil { r := *ev.Response; finalResp = &r } ; out <- ev }; if streamErr == nil { resp := Response{Provider: string(req.Provider), Model: req.Model, Content: text, ToolCalls: calls, Reasoning: reasoning}; if finalResp != nil { resp = *finalResp; if resp.Provider == "" { resp.Provider = string(req.Provider) }; if resp.Model == "" { resp.Model = req.Model } }; if recordErr := session.RecordResponse(requestID, resp, nil); recordErr != nil { out <- Event{Type: EventError, Err: recordErr}; return }; return }; resp := Response{Provider: string(req.Provider), Model: req.Model, Content: text, ToolCalls: calls, Reasoning: reasoning}; if finalResp != nil { resp = *finalResp }; if recordErr := session.RecordResponse(requestID, resp, streamErr); recordErr != nil { out <- Event{Type: EventError, Err: recordErr}; return }; if started || attempt >= policy.MaxAttempts || !retryable(streamErr) { out <- Event{Type: EventError, Err: streamErr}; return }; if err := sleepBackoff(ctx, policy, attempt); err != nil { out <- Event{Type: EventError, Err: err}; return } } }(); return out, nil }
func (c *RouterClient) StreamTurn(ctx context.Context, session *Session, user Turn, req Request) (<-chan Event, error) { before := session.History(); session.Append(user); req.Messages = session.History(); ch, err := c.Stream(ctx, session, req); if err != nil { session.ReplaceHistory(before); return nil, err }; out := make(chan Event, 16); go func() { defer close(out); var text []ContentPart; var calls []ToolCall; var reasoning *ReasoningState; for ev := range ch { out <- ev; if ev.Type == EventText && ev.Text != "" { text = append(text, ContentPart{Type: ContentText, Text: ev.Text}) }; if ev.Type == EventReasoning && ev.Reasoning != nil { r := *ev.Reasoning; if reasoning == nil { reasoning = &ReasoningState{} }; if r.ID != "" { reasoning.ID = r.ID }; reasoning.Text += r.Text }; if ev.Type == EventToolCall && ev.ToolCall != nil { calls = append(calls, *ev.ToolCall) }; if ev.Type == EventDone { if len(text) > 0 || reasoning != nil { session.Append(Turn{Role: RoleModel, Content: text, Reasoning: reasoning}) }; for _, call := range calls { call := call; session.Append(Turn{Role: RoleToolCall, ToolCall: &call}) }; return }; if ev.Type == EventError { session.ReplaceHistory(before); return } }; session.ReplaceHistory(before) }(); return out, nil }
