package sdk

import (
	"strings"
	"context"
	"database/sql"
	"errors"
	"fmt"
	"sync"
)

type routeKey struct { provider ProviderID; model string }
type Router struct { mu sync.RWMutex; routes map[routeKey]ModelRoute; providers map[ProviderID]ProviderConfig; catalogs map[ProviderID][]Model; catalogReady map[ProviderID]bool }
func NewRouter() *Router { return &Router{routes: make(map[routeKey]ModelRoute), providers: make(map[ProviderID]ProviderConfig), catalogs: make(map[ProviderID][]Model), catalogReady: make(map[ProviderID]bool)} }
func (r *Router) RegisterProvider(config ProviderConfig) { if config.ID == "" || config.Adapter == "" { panic("sdk: invalid provider config") }; r.mu.Lock(); defer r.mu.Unlock(); r.providers[config.ID] = config; delete(r.catalogs, config.ID); r.catalogReady[config.ID] = false }
func (r *Router) Provider(provider ProviderID) (ProviderConfig, error) { r.mu.RLock(); config, ok := r.providers[provider]; r.mu.RUnlock(); if !ok { return ProviderConfig{}, fmt.Errorf("sdk: provider %q is not registered", provider) }; return config, nil }
func (r *Router) Register(route ModelRoute) { if route.Provider == "" || route.Model == "" || route.Adapter == "" { panic("sdk: invalid model route") }; r.mu.Lock(); defer r.mu.Unlock(); r.routes[routeKey{route.Provider, route.Model}] = route }
func (r *Router) RefreshModels(ctx context.Context, provider ProviderID, adapter Provider) error { config, err := r.Provider(provider); if err != nil { return err }; lister, ok := adapter.(ModelLister); if !ok { return fmt.Errorf("sdk: adapter %q does not support model discovery", config.Adapter) }; if config.Keys == nil { return errors.New("sdk: provider has no key pool") }; key, err := config.Keys.Current(); if err != nil { return err }; p := adapter; if kp, ok := p.(KeyedProvider); ok { p = kp.WithAPIKey(key) }; if ep, ok := p.(EndpointProvider); ok && config.BaseURL != "" { p = ep.WithBaseURL(config.BaseURL) }; if len(config.Headers) > 0 { if hp, ok := p.(HeaderedProvider); ok { p = hp.WithHeaders(config.Headers) } }; lister, ok = p.(ModelLister); if !ok { return fmt.Errorf("sdk: configured adapter %q cannot discover models after configuration", config.Adapter) }; models, err := lister.ListModels(ctx, key); if err != nil { return err }; clean := make([]Model, 0, len(models)); seen := make(map[string]struct{}); for _, model := range models { if model.ID == "" { continue }; if _, exists := seen[model.ID]; exists { continue }; seen[model.ID] = struct{}{}; clean = append(clean, model) }; clean = filterFreeModels(clean, config.FreeOnly); r.mu.Lock(); r.catalogs[provider] = clean; r.catalogReady[provider] = true; r.mu.Unlock(); return nil }
func filterFreeModels(models []Model, freeOnly bool) []Model { if !freeOnly { return models }; out := make([]Model, 0, len(models)); for _, model := range models { if strings.HasSuffix(strings.ToLower(strings.TrimSpace(model.ID)), "-free") { out = append(out, model) } }; return out }
func (r *Router) Models(provider ProviderID) []Model { r.mu.RLock(); models := append([]Model(nil), r.catalogs[provider]...); r.mu.RUnlock(); return models }
func (r *Router) Resolve(provider ProviderID, model string) (ModelRoute, error) { if provider == "" { return ModelRoute{}, errors.New("sdk: provider is required") }; if model == "" { return ModelRoute{}, errors.New("sdk: model is required") }; r.mu.RLock(); config, providerOK := r.providers[provider]; ready := r.catalogReady[provider]; route, staticOK := r.routes[routeKey{provider, model}]; if ready { for _, discovered := range r.catalogs[provider] { if discovered.ID == model { r.mu.RUnlock(); return ModelRoute{Provider: provider, Model: model, Adapter: config.Adapter}, nil } }; r.mu.RUnlock(); return ModelRoute{}, fmt.Errorf("sdk: model %q is not available for provider=%q", model, provider) }; r.mu.RUnlock(); if staticOK { return route, nil }; if providerOK { return ModelRoute{}, fmt.Errorf("sdk: model catalogue for provider=%q has not been refreshed", provider) }; return ModelRoute{}, fmt.Errorf("sdk: no route for provider=%q model=%q", model, provider) }

type Session struct { mu sync.RWMutex; config SessionConfig; keys *KeyPool; history []Turn; store *SessionDB }
func NewSession(config SessionConfig, keys *KeyPool) *Session { return &Session{config: config, keys: keys} }
func OpenSession(path string, config SessionConfig, keys *KeyPool) (*Session, error) { store, err := OpenSessionDB(path); if err != nil { return nil, err }; persisted, loadErr := store.LoadSession(config.ID); if loadErr == nil { config = persisted } else if !errors.Is(loadErr, sql.ErrNoRows) { store.Close(); return nil, loadErr } else if err := store.SaveSession(config); err != nil { store.Close(); return nil, err }; history, err := store.LoadHistory(config.ID); if err != nil { store.Close(); return nil, err }; return &Session{config: config, keys: keys, history: history, store: store}, nil }
func (s *Session) Close() error { s.mu.RLock(); store := s.store; s.mu.RUnlock(); if store == nil { return nil }; return store.Close() }
func (s *Session) ID() string { return s.config.ID }
func (s *Session) Config() SessionConfig { s.mu.RLock(); defer s.mu.RUnlock(); c := s.config; if c.Temperature != nil { v := *c.Temperature; c.Temperature = &v }; return c }
func (s *Session) APIKey() (string, error) { s.mu.RLock(); keys, index := s.keys, s.config.KeyIndex; s.mu.RUnlock(); if keys == nil { return "", errors.New("sdk: session has no key pool") }; return keys.At(index) }
func (s *Session) RotateAPIKey() (string, error) { s.mu.Lock(); defer s.mu.Unlock(); if s.keys == nil { return "", errors.New("sdk: session has no key pool") }; key, err := s.keys.Rotate(); if err != nil { return "", err }; s.config.KeyIndex = s.keys.IndexOfCurrent(); return key, nil }
func (s *Session) History() []Turn { s.mu.RLock(); defer s.mu.RUnlock(); return cloneTurns(s.history) }
func (s *Session) Append(turns ...Turn) { if len(turns) == 0 { return }; s.mu.Lock(); defer s.mu.Unlock(); cloned := cloneTurns(turns); start := len(s.history); s.history = append(s.history, cloned...); if s.store != nil { if err := s.store.AppendTurns(s.config.ID, cloned, start); err != nil { s.history = s.history[:start]; panic(fmt.Sprintf("sdk: persist session append: %v", err)) } } }
func (s *Session) ReplaceHistory(turns []Turn) { repaired := repairTurns(cloneTurns(turns)); s.mu.Lock(); defer s.mu.Unlock(); old := s.history; s.history = repaired; if s.store != nil { if err := s.store.ReplaceTurns(s.config.ID, repaired); err != nil { s.history = old; panic(fmt.Sprintf("sdk: persist session replace: %v", err)) } } }
func (s *Session) RepairHistory() { s.ReplaceHistory(s.History()) }
func (s *Session) RecordRequest(attempt int, req Request) (int64, error) { s.mu.RLock(); store, id := s.store, s.config.ID; s.mu.RUnlock(); if store == nil { return 0, nil }; return store.RecordRequest(id, attempt, req) }
func (s *Session) RecordResponse(requestID int64, resp Response, err error) error { s.mu.RLock(); store := s.store; s.mu.RUnlock(); if store == nil { return nil }; return store.RecordResponse(requestID, resp, err) }
func cloneTurns(in []Turn) []Turn { out := make([]Turn, len(in)); copy(out, in); for i := range out { out[i] = cloneTurn(out[i]) }; return out }
func cloneTurn(turn Turn) Turn { turn.Content = append([]ContentPart(nil), turn.Content...); if turn.ToolCall != nil { v := *turn.ToolCall; turn.ToolCall = &v }; if turn.ToolResult != nil { v := *turn.ToolResult; turn.ToolResult = &v }; if turn.Reasoning != nil { v := *turn.Reasoning; turn.Reasoning = &v }; return turn }
func repairTurns(in []Turn) []Turn { out := make([]Turn, 0, len(in)); pending := make(map[string]bool); for _, turn := range in { switch turn.Role { case RoleUser, RoleModel: out = append(out, turn); case RoleToolCall: if turn.ToolCall == nil || turn.ToolCall.ID == "" || turn.ToolCall.Name == "" || pending[turn.ToolCall.ID] { continue }; pending[turn.ToolCall.ID] = true; out = append(out, turn); case RoleToolResult: if turn.ToolResult == nil || turn.ToolResult.ID == "" || !pending[turn.ToolResult.ID] { continue }; delete(pending, turn.ToolResult.ID); out = append(out, turn) } }; if len(pending) == 0 { return out }; final := out[:0]; for _, turn := range out { if turn.Role == RoleToolCall && pending[turn.ToolCall.ID] { continue }; final = append(final, turn) }; return final }
