package tools

import (
	"bufio"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/gorilla/websocket"
)

type BrowserClientConfig struct { Browser string; Profile string; Headless bool; AllowPrivate bool; Display string; Mode string; CDPEndpoint string; PIDFile string; Lazy bool; IdleTimeout, NavigationTimeout, ActionTimeout, SnapshotTimeout time.Duration }
type BrowserClient struct { cfg BrowserClientConfig; mu, stateMu sync.Mutex; startMu sync.Mutex; ready bool; cmd *exec.Cmd; pid int; conn *websocket.Conn; seq int64; sessions map[string]*browserSession; firefoxBiDi bool; bidiSessionID string; bidiEndpoint string; pipeMode bool; pipeIn, pipeOut *os.File; pipeReader *bufio.Reader }
type browserSession struct { TargetID, CDPSession string; Refs map[string]browserRef; LastUsed time.Time }
type browserRef struct { Role, Name string; BackendNodeID int64 }

type pageMetadataResult struct { URL string `json:"url"`; Title string `json:"title"` }

func NewBrowserClient(config BrowserClientConfig) *BrowserClient { if config.Browser==""{config.Browser="firefox"};if config.Mode==""{config.Mode="managed"};if config.IdleTimeout<=0{config.IdleTimeout=30*time.Minute};if config.NavigationTimeout<=0{config.NavigationTimeout=30*time.Second};if config.ActionTimeout<=0{config.ActionTimeout=10*time.Second};if config.SnapshotTimeout<=0{config.SnapshotTimeout=10*time.Second};return &BrowserClient{cfg:config,sessions:make(map[string]*browserSession)} }
func NewBrowserClientForTest(_ string,_ string,config BrowserClientConfig)*BrowserClient{return NewBrowserClient(config)}
func(c *BrowserClient)Start(ctx context.Context)error{c.startMu.Lock();defer c.startMu.Unlock();c.mu.Lock();if c.ready{c.mu.Unlock();return nil};c.mu.Unlock();binary,err:=findBrowser(c.cfg.Browser);if err!=nil{return err};profile,err:=filepath.Abs(c.cfg.Profile);if err!=nil{return fmt.Errorf("browser profile: %w",err)};if err:=os.MkdirAll(profile,0o700);err!=nil{return fmt.Errorf("browser: create profile: %w",err)};if isFirefox(binary,c.cfg.Browser){return c.startFirefox(ctx,binary,profile)};return c.startChromiumPipe(ctx,binary,profile)}
func chromiumPipeArgs(profile string,headless bool)[]string{args:=[]string{"--remote-debugging-pipe","--user-data-dir="+profile,"--no-first-run","--no-default-browser-check"};if headless{args=append(args,"--headless=new")}else if runtime.GOOS=="linux"{args=append(args,"--disable-gpu")};return args}
func(c *BrowserClient)startChromiumPipe(ctx context.Context,binary,profile string)error{
args:=chromiumPipeArgs(profile,c.cfg.Headless);
if runtime.GOOS=="linux"&&os.Geteuid()==0{args=append(args,"--no-sandbox")};
inR,inW,err:=os.Pipe();if err!=nil{return fmt.Errorf("chromium pipe: %w",err)};
outR,outW,err:=os.Pipe();if err!=nil{_=inR.Close();_=inW.Close();return fmt.Errorf("chromium pipe: %w",err)};
cmd:=exec.Command(binary,args...);cmd.ExtraFiles=[]*os.File{inR,outW};
if displayEnv:=browserDisplayEnv(c.cfg.Display);displayEnv!=nil{cmd.Env=displayEnv};
if err:=cmd.Start();err!=nil{_=inR.Close();_=inW.Close();_=outR.Close();_=outW.Close();return fmt.Errorf("start browser %q: %w",binary,err)};
_=inR.Close();_=outW.Close();
c.mu.Lock();c.cmd=cmd;c.pipeIn=inW;c.pipeOut=outR;c.pipeReader=bufio.NewReader(outR);c.pipeMode=true;c.mu.Unlock();
handshake,handshakeCancel:=context.WithTimeout(ctx,15*time.Second);defer handshakeCancel();
var probe struct{Targets []any `json:"targetInfos"`};
if err:=c.commandWithTimeout(handshake,"Target.getTargets",map[string]any{},"",&probe,15*time.Second);err!=nil{_=inW.Close();_=outR.Close();_=cmd.Process.Kill();_=cmd.Wait();c.mu.Lock();c.cmd=nil;c.pipeIn=nil;c.pipeOut=nil;c.pipeReader=nil;c.pipeMode=false;c.mu.Unlock();return fmt.Errorf("chromium pipe handshake: %w",err)};
c.mu.Lock();c.ready=true;if cmd!=nil&&cmd.Process!=nil{c.pid=cmd.Process.Pid};pidFile:=c.cfg.PIDFile;pid:=c.pid;c.mu.Unlock();if pidFile!=""&&pid>0{_=os.WriteFile(pidFile,[]byte(strconv.Itoa(pid)+"\n"),0o644)};
return nil}
func writeFullPipe(f *os.File,data []byte)(int,error){w:=0;for w<len(data){n,err:=f.Write(data[w:]);w+=n;if err!=nil{return w,err}};return w,nil}
func readPipeFrame(ctx context.Context,r *bufio.Reader,timeout time.Duration)([]byte,error){type res struct{b []byte;err error};ch:=make(chan res,1);go func(){b,err:=r.ReadBytes(0);ch<-res{b,err}}();var timer<-chan time.Time;if timeout>0{t:=time.NewTimer(timeout);defer t.Stop();timer=t.C};select{case <-ctx.Done():return nil,ctx.Err();case <-timer:return nil,fmt.Errorf("cdp pipe read timeout");case v:=<-ch:if v.err!=nil{return nil,v.err};b:=v.b;if len(b)>0&&b[len(b)-1]==0{b=b[:len(b)-1]};return b,nil}}
func(c *BrowserClient)pipeCommandLocked(ctx context.Context,method string,params any,sessionID string,result any,timeout time.Duration)error{if c.pipeIn==nil||c.pipeOut==nil||c.pipeReader==nil{return errors.New("browser is unavailable")};c.seq++;id:=c.seq;message:=map[string]any{"id":id,"method":method,"params":params};if sessionID!=""{message["sessionId"]=sessionID};data,err:=json.Marshal(message);if err!=nil{return err};data=append(data,0);if _,err:=writeFullPipe(c.pipeIn,data);err!=nil{return err};if timeout<=0{timeout=10*time.Second};deadline:=time.Now().Add(timeout);for{remaining:=time.Until(deadline);if remaining<=0{return fmt.Errorf("cdp pipe read timeout")};frame,err:=readPipeFrame(ctx,c.pipeReader,remaining);if err!=nil{return err};if len(frame)==0{continue};var envelope struct{ID int64 `json:"id"`;Result json.RawMessage `json:"result"`;Error *struct{Code int `json:"code"`;Message string `json:"message"`} `json:"error"`};if err:=json.Unmarshal(frame,&envelope);err!=nil{continue};if envelope.ID!=id{continue};if envelope.Error!=nil{return fmt.Errorf("cdp %d: %s",envelope.Error.Code,envelope.Error.Message)};if result!=nil&&len(envelope.Result)>0{return json.Unmarshal(envelope.Result,result)};return nil}}
func(c *BrowserClient)startFirefox(ctx context.Context,binary,profile string)error{
port:=freeLoopbackPort();
args:=[]string{"-profile",profile,"--remote-debugging-address=127.0.0.1","--remote-debugging-port="+strconv.Itoa(port),"--no-first-run","--no-remote"};
if c.cfg.Headless{args=append(args,"--headless")}else if runtime.GOOS=="linux"{args=append(args,"--disable-gpu")};
if runtime.GOOS=="linux"&&os.Geteuid()==0{args=append(args,"--no-sandbox")};
cmd:=exec.Command(binary,args...);
if displayEnv:=browserDisplayEnv(c.cfg.Display);displayEnv!=nil{cmd.Env=displayEnv};
if err:=cmd.Start();err!=nil{return fmt.Errorf("start browser %q: %w",binary,err)};
addr:="127.0.0.1:"+strconv.Itoa(port);
deadline:=time.Now().Add(15*time.Second);
tcpReady:=false;
for time.Now().Before(deadline){
d,err:=net.DialTimeout("tcp",addr,200*time.Millisecond);
if err==nil{d.Close();tcpReady=true;break};
if cmd.ProcessState!=nil{break};
time.Sleep(200*time.Millisecond)};
if !tcpReady{_=cmd.Process.Kill();_=cmd.Wait();return fmt.Errorf("browser did not expose a DevTools endpoint")};
wsURL:=fmt.Sprintf("ws://127.0.0.1:%d/session",port);
var conn *websocket.Conn;
var dialErr error;
var writeErr error;
for attempt:=0;attempt<3;attempt++{
conn,_,dialErr=websocket.DefaultDialer.DialContext(ctx,wsURL,nil);
if dialErr!=nil{if attempt==2{_=cmd.Process.Kill();_=cmd.Wait();return fmt.Errorf("firefox-bidi probe /session: %w",dialErr)};time.Sleep(time.Second);continue};
_ = conn.SetWriteDeadline(time.Now().Add(20*time.Second));
if writeErr=conn.WriteJSON(map[string]any{"id":1,"method":"session.new","params":map[string]any{"capabilities":map[string]any{"acceptInsecureCerts":true}}});writeErr==nil{break};
conn.Close();conn=nil;
if attempt==2{_=cmd.Process.Kill();_=cmd.Wait();return fmt.Errorf("firefox-bidi session.new write: %w",writeErr)};
time.Sleep(time.Second)};
if conn==nil{if writeErr!=nil{_=cmd.Process.Kill();_=cmd.Wait();return fmt.Errorf("firefox-bidi session.new write: %w",writeErr)};_=cmd.Process.Kill();_=cmd.Wait();return fmt.Errorf("firefox-bidi probe /session: %w",dialErr)};
_ = conn.SetReadDeadline(time.Now().Add(10*time.Second));
var bidiSessionID string;
for{
_,data,err:=conn.ReadMessage();
if err!=nil{conn.Close();_=cmd.Process.Kill();_=cmd.Wait();return fmt.Errorf("firefox-bidi session.new read: %w",err)};
var env struct{ID *int64 `json:"id"`;Result json.RawMessage `json:"result"`};
if err:=json.Unmarshal(data,&env);err!=nil{continue};
if env.ID==nil||*env.ID!=1{continue};
if len(env.Result)==0{continue};
var res map[string]any;
if err:=json.Unmarshal(env.Result,&res);err!=nil{continue};
for _,k:=range []string{"sessionId","sessionID","session_id"}{if v,ok:=res[k];ok{if s,ok:=v.(string);ok&&s!=""{bidiSessionID=s;break}}};
if bidiSessionID==""{continue};
break};
conn.SetReadDeadline(time.Time{});
c.finishStart(cmd,conn);
c.mu.Lock();c.seq=1;c.firefoxBiDi=true;c.bidiSessionID=bidiSessionID;c.bidiEndpoint=wsURL;c.mu.Unlock();
return nil}
func(c *BrowserClient)finishStart(cmd *exec.Cmd,conn *websocket.Conn){c.mu.Lock();c.cmd,c.conn,c.ready=cmd,conn,true;if cmd!=nil&&cmd.Process!=nil{c.pid=cmd.Process.Pid};pidFile:=c.cfg.PIDFile;pid:=c.pid;c.mu.Unlock();if pidFile!=""&&pid>0{_=os.WriteFile(pidFile,[]byte(strconv.Itoa(pid)+"\n"),0o644)}}
func freeLoopbackPort()int{l,err:=net.Listen("tcp","127.0.0.1:0");if err!=nil{return 9222};defer l.Close();if a,ok:=l.Addr().(*net.TCPAddr);ok&&a.Port>0{return a.Port};return 9222}
func(c *BrowserClient)Close()error{c.mu.Lock();conn,cmd:=c.conn,c.cmd;pipeIn,pipeOut:=c.pipeIn,c.pipeOut;pid:=c.pid;pidFile:=c.cfg.PIDFile;c.conn,c.cmd,c.ready=nil,nil,false;c.pipeIn,c.pipeOut,c.pipeReader=nil,nil,nil;c.pipeMode=false;c.pid=0;c.mu.Unlock();if conn!=nil{_=conn.Close()};if pipeIn!=nil{_=pipeIn.Close()};if pipeOut!=nil{_=pipeOut.Close()};if cmd!=nil&&cmd.Process!=nil{pid=cmd.Process.Pid};if pid>0{killBrowserPID(pid)};if cmd!=nil{done:=make(chan struct{});go func(){_=cmd.Wait();close(done)}();select{case<-done:case<-time.After(2*time.Second):if cmd.Process!=nil{_=cmd.Process.Kill()};<-done}};if pidFile!=""{_=os.Remove(pidFile)};return nil}
func syscallSignalZero()os.Signal{return syscall.Signal(0)}
func killBrowserPID(pid int){if pid<=0{return};proc,err:=os.FindProcess(pid);if err!=nil{return};_=proc.Signal(os.Interrupt);deadline:=time.Now().Add(2*time.Second);for time.Now().Before(deadline){if err:=proc.Signal(syscallSignalZero());err!=nil{return};time.Sleep(100*time.Millisecond)};_=proc.Kill()}
func(c *BrowserClient)Ready()bool{c.mu.Lock();defer c.mu.Unlock();return c.ready}
func(c *BrowserClient)ensureStarted(ctx context.Context)error{c.mu.Lock();ready:=c.ready||c.conn!=nil;c.mu.Unlock();if ready{return nil};if !c.cfg.Lazy{return errors.New("browser is unavailable")};if c.cfg.Mode=="attach"{return c.Attach(ctx,c.cfg.CDPEndpoint)};return c.Start(ctx)}
func(c *BrowserClient)Call(ctx context.Context,method string,params any,result any)error{if err:=c.ensureStarted(ctx);err!=nil{return err};if c.isBiDi(){switch method{case"browser.open":var a struct{SessionID string `json:"session_id"`};if err:=marshalInto(params,&a);err!=nil{return err};return c.bidiOpen(ctx,a.SessionID,result);case"browser.navigate":var a struct{SessionID string `json:"session_id"`;URL string `json:"url"`};if err:=marshalInto(params,&a);err!=nil{return err};return c.bidiNavigate(ctx,a.SessionID,a.URL,result);case"browser.snapshot":var a struct{SessionID string `json:"session_id"`};if err:=marshalInto(params,&a);err!=nil{return err};return c.bidiSnapshot(ctx,a.SessionID,result);case"browser.close":var a struct{SessionID string `json:"session_id"`};if err:=marshalInto(params,&a);err!=nil{return err};return c.bidiCloseSession(ctx,a.SessionID,result);default:return fmt.Errorf("firefox-bidi-unsupported: method %q is not supported on Firefox BiDi",method)}};c.mu.Lock();if !c.ready||(c.conn==nil&&!c.pipeMode){c.mu.Unlock();return errors.New("browser is unavailable")};c.mu.Unlock();switch method{case"browser.open":var a struct{SessionID string `json:"session_id"`};if err:=marshalInto(params,&a);err!=nil{return err};return c.open(ctx,a.SessionID,result);case"browser.close":var a struct{SessionID string `json:"session_id"`};if err:=marshalInto(params,&a);err!=nil{return err};return c.closeSession(ctx,a.SessionID,result);case"browser.navigate":var a struct{SessionID string `json:"session_id"`;URL string `json:"url"`};if err:=marshalInto(params,&a);err!=nil{return err};return c.navigate(ctx,a.SessionID,a.URL,result);case"browser.snapshot":var a struct{SessionID string `json:"session_id"`};if err:=marshalInto(params,&a);err!=nil{return err};return c.snapshot(ctx,a.SessionID,result);case"browser.click","browser.fill","browser.press","browser.select":return c.actionRef(ctx,params,strings.TrimPrefix(method,"browser."),result);case"browser.scroll":return c.scroll(ctx,params,result);case"browser.get_text":return c.getText(ctx,params,result);case"browser.screenshot":return c.screenshot(ctx,params,result);default:return fmt.Errorf("unsupported browser method %q",method)}}
func(c *BrowserClient)open(ctx context.Context,sessionID string,out any)error{if strings.TrimSpace(sessionID)==""{return errors.New("session_id is required")};c.stateMu.Lock();defer c.stateMu.Unlock();if s:=c.sessions[sessionID];s!=nil{meta,_:=c.pageMetadata(ctx,s);return jsonInto(out,map[string]any{"session_id":sessionID,"context_id":sessionID,"page_id":s.TargetID,"url":meta.URL,"title":meta.Title})};var target struct{TargetID string `json:"targetId"`};if err:=c.command(ctx,"Target.createTarget",map[string]any{"url":"about:blank"},"",&target);err!=nil{return err};var attached struct{SessionID string `json:"sessionId"`};if err:=c.command(ctx,"Target.attachToTarget",map[string]any{"targetId":target.TargetID,"flatten":true},"",&attached);err!=nil{return err};c.sessions[sessionID]=&browserSession{TargetID:target.TargetID,CDPSession:attached.SessionID,Refs:make(map[string]browserRef),LastUsed:time.Now()};return jsonInto(out,map[string]any{"session_id":sessionID,"context_id":sessionID,"page_id":target.TargetID,"url":"about:blank","title":""})}
func(c *BrowserClient)closeSession(ctx context.Context,sessionID string,out any)error{c.stateMu.Lock();defer c.stateMu.Unlock();s:=c.sessions[sessionID];if s==nil{return jsonInto(out,map[string]any{"closed":false})};_=c.command(ctx,"Target.closeTarget",map[string]any{"targetId":s.TargetID},"",nil);delete(c.sessions,sessionID);return jsonInto(out,map[string]any{"closed":true})}
func(c *BrowserClient)navigate(ctx context.Context,sessionID,url string,out any)error{s,err:=c.getSession(sessionID);if err!=nil{return err};if url==""{return errors.New("url is required")};var nav struct{ErrorText string `json:"errorText"`};if err:=c.commandWithTimeout(ctx,"Page.navigate",map[string]any{"url":url},s.CDPSession,&nav,c.cfg.NavigationTimeout);err!=nil{return err};if nav.ErrorText!=""{return errors.New(nav.ErrorText)};time.Sleep(150*time.Millisecond);meta,_:=c.pageMetadata(ctx,s);c.touch(s);return jsonInto(out,map[string]any{"page_id":s.TargetID,"url":meta.URL,"title":meta.Title,"status":200})}
type axNode struct{NodeID string `json:"nodeId"`;BackendDOMNodeID int64 `json:"backendDOMNodeId"`;Ignored bool `json:"ignored"`;Role axValue `json:"role"`;Name axValue `json:"name"`;ChildIDs []string `json:"childIds"`;ParentID string `json:"parentId"`};type axValue struct{Value any `json:"value"`}
func(c *BrowserClient)snapshot(ctx context.Context,sessionID string,out any)error{s,err:=c.getSession(sessionID);if err!=nil{return err};var tree struct{Nodes []axNode `json:"nodes"`};if err:=c.commandWithTimeout(ctx,"Accessibility.getFullAXTree",map[string]any{},s.CDPSession,&tree,c.cfg.SnapshotTimeout);err!=nil{return err};lines,refs:=buildSnapshot(tree.Nodes);c.stateMu.Lock();s.Refs=refs;s.LastUsed=time.Now();c.stateMu.Unlock();meta,_:=c.pageMetadata(ctx,s);return jsonInto(out,map[string]any{"page_id":s.TargetID,"url":meta.URL,"title":meta.Title,"snapshot":strings.Join(lines,"\n")})}
func buildSnapshot(nodes []axNode)([]string,map[string]browserRef){byID:=make(map[string]axNode,len(nodes));for _,n:=range nodes{byID[n.NodeID]=n};refs:=make(map[string]browserRef);var lines []string;counter:=0;var walk func(string,int);walk=func(id string,depth int){n,ok:=byID[id];if !ok||n.Ignored{return};role:=fmt.Sprint(n.Role.Value);name:=strings.TrimSpace(fmt.Sprint(n.Name.Value));if role=="RootWebArea"{role="page"};line:=strings.Repeat("  ",depth)+"- "+role;if name!=""&&name!="<nil>"{line+=" \""+escapeSnapshotName(name)+"\""};if actionableRole(role)&&n.BackendDOMNodeID>0{counter++;ref:=fmt.Sprintf("e%d",counter);line+=" [ref="+ref+"]";refs[ref]=browserRef{Role:role,Name:name,BackendNodeID:n.BackendDOMNodeID}};if role!="none"&&role!="generic"{lines=append(lines,line)};for _,child:=range n.ChildIDs{walk(child,depth+1)}};roots:=make([]string,0);for _,n:=range nodes{if n.ParentID==""{roots=append(roots,n.NodeID)}};for _,id:=range roots{walk(id,0)};return lines,refs}
func actionableRole(role string)bool{switch strings.ToLower(role){case"button","link","textbox","combobox","checkbox","radio","tab","menuitem","option","slider","spinbutton":return true;default:return false}}
func escapeSnapshotName(s string)string{return strings.NewReplacer("\\","\\\\","\"","\\\"").Replace(s)}
func(c *BrowserClient)actionRef(ctx context.Context,params any,action string,out any)error{var a struct{SessionID string `json:"session_id"`;Ref string `json:"ref"`;Text string `json:"text"`;Key string `json:"key"`;Value string `json:"value"`};if err:=marshalInto(params,&a);err!=nil{return err};s,err:=c.getSession(a.SessionID);if err!=nil{return err};c.stateMu.Lock();descriptor,ok:=s.Refs[a.Ref];c.stateMu.Unlock();if !ok{return fmt.Errorf("stale_reference: reference %s is not valid; take a new browser_snapshot",a.Ref)};var object struct{Object struct{ObjectID string `json:"objectId"`} `json:"object"`};if err:=c.commandWithTimeout(ctx,"DOM.resolveNode",map[string]any{"backendNodeId":descriptor.BackendNodeID},s.CDPSession,&object,c.cfg.ActionTimeout);err!=nil{return err};if object.Object.ObjectID==""{return fmt.Errorf("stale_reference: reference %s no longer resolves",a.Ref)};switch action{case"click":return c.callElement(ctx,s,object.Object.ObjectID,"(el)=>el.click()",nil,out);case"fill":return c.callElement(ctx,s,object.Object.ObjectID,"(el,v)=>{el.focus();el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));}",[]any{map[string]any{"value":a.Text}},out);case"select":return c.callElement(ctx,s,object.Object.ObjectID,"(el,v)=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));}",[]any{map[string]any{"value":a.Value}},out);case"press":if err:=c.callElement(ctx,s,object.Object.ObjectID,"(el)=>el.focus()",nil,nil);err!=nil{return err};key:=a.Key;if key==""{key="Enter"};if err:=c.commandWithTimeout(ctx,"Input.dispatchKeyEvent",map[string]any{"type":"keyDown","key":key},s.CDPSession,&struct{}{},c.cfg.ActionTimeout);err!=nil{return err};if err:=c.commandWithTimeout(ctx,"Input.dispatchKeyEvent",map[string]any{"type":"keyUp","key":key},s.CDPSession,&struct{}{},c.cfg.ActionTimeout);err!=nil{return err};return jsonInto(out,map[string]any{"page_id":s.TargetID,"ok":true});default:return fmt.Errorf("unsupported browser action %q",action)}}
func(c *BrowserClient)callElement(ctx context.Context,s *browserSession,objectID,fn string,args []any,out any)error{callArgs:=map[string]any{"objectId":objectID,"functionDeclaration":fn,"returnByValue":true};if args!=nil{callArgs["arguments"]=args};if err:=c.commandWithTimeout(ctx,"Runtime.callFunctionOn",callArgs,s.CDPSession,&struct{}{},c.cfg.ActionTimeout);err!=nil{return err};c.touch(s);return jsonInto(out,map[string]any{"page_id":s.TargetID,"ok":true})}
func(c *BrowserClient)scroll(ctx context.Context,params any,out any)error{var a struct{SessionID string `json:"session_id"`;Direction string `json:"direction"`;Amount int `json:"amount"`};if err:=marshalInto(params,&a);err!=nil{return err};if a.Amount<=0{a.Amount=700};s,err:=c.getSession(a.SessionID);if err!=nil{return err};delta:=a.Amount;if strings.EqualFold(a.Direction,"up"){delta=-delta};if err:=c.commandWithTimeout(ctx,"Runtime.evaluate",map[string]any{"expression":fmt.Sprintf("window.scrollBy(0,%d)",delta),"returnByValue":true},s.CDPSession,&struct{}{},c.cfg.ActionTimeout);err!=nil{return err};c.touch(s);return jsonInto(out,map[string]any{"page_id":s.TargetID,"direction":a.Direction,"amount":a.Amount})}
func(c *BrowserClient)getText(ctx context.Context,params any,out any)error{var a struct{SessionID string `json:"session_id"`;Ref string `json:"ref"`};if err:=marshalInto(params,&a);err!=nil{return err};s,err:=c.getSession(a.SessionID);if err!=nil{return err};if a.Ref==""{var v struct{Result struct{Value string `json:"value"`} `json:"result"`};if err:=c.commandWithTimeout(ctx,"Runtime.evaluate",map[string]any{"expression":"document.body?.innerText || ''","returnByValue":true},s.CDPSession,&v,c.cfg.ActionTimeout);err!=nil{return err};return jsonInto(out,map[string]any{"page_id":s.TargetID,"text":v.Result.Value})};c.stateMu.Lock();descriptor,ok:=s.Refs[a.Ref];c.stateMu.Unlock();if !ok{return fmt.Errorf("stale_reference: reference %s is not valid; take a new browser_snapshot",a.Ref)};var object struct{Object struct{ObjectID string `json:"objectId"`} `json:"object"`};if err:=c.commandWithTimeout(ctx,"DOM.resolveNode",map[string]any{"backendNodeId":descriptor.BackendNodeID},s.CDPSession,&object,c.cfg.ActionTimeout);err!=nil{return err};var v struct{Result struct{Value string `json:"value"`} `json:"result"`};if err:=c.commandWithTimeout(ctx,"Runtime.callFunctionOn",map[string]any{"objectId":object.Object.ObjectID,"functionDeclaration":"(el)=>el.innerText || el.value || ''","returnByValue":true},s.CDPSession,&v,c.cfg.ActionTimeout);err!=nil{return err};return jsonInto(out,map[string]any{"page_id":s.TargetID,"text":v.Result.Value})}
func(c *BrowserClient)screenshot(ctx context.Context,params any,out any)error{var a struct{SessionID string `json:"session_id"`;FullPage bool `json:"full_page"`};if err:=marshalInto(params,&a);err!=nil{return err};s,err:=c.getSession(a.SessionID);if err!=nil{return err};var shot struct{Data string `json:"data"`};if err:=c.commandWithTimeout(ctx,"Page.captureScreenshot",map[string]any{"format":"png","captureBeyondViewport":a.FullPage},s.CDPSession,&shot,c.cfg.ActionTimeout);err!=nil{return err};return jsonInto(out,map[string]any{"page_id":s.TargetID,"content_type":"image/png","base64":shot.Data})}
func(c *BrowserClient)getSession(id string)(*browserSession,error){if strings.TrimSpace(id)==""{return nil,errors.New("session_id is required")};c.stateMu.Lock();defer c.stateMu.Unlock();s:=c.sessions[id];if s==nil{return nil,fmt.Errorf("browser session %s is not open",id)};return s,nil}
func(c *BrowserClient)touch(s *browserSession){c.stateMu.Lock();s.LastUsed=time.Now();c.stateMu.Unlock()}
func(c *BrowserClient)pageMetadata(ctx context.Context,s *browserSession)(pageMetadataResult,error){var v struct{Result struct{Value pageMetadataResult `json:"value"`} `json:"result"`};if err:=c.command(ctx,"Runtime.evaluate",map[string]any{"expression":"({url:location.href,title:document.title})","returnByValue":true},s.CDPSession,&v);err!=nil{return pageMetadataResult{},err};return v.Result.Value,nil}
func(c *BrowserClient)command(ctx context.Context,method string,params any,sessionID string,result any)error{return c.commandWithTimeout(ctx,method,params,sessionID,result,c.cfg.ActionTimeout)}
func(c *BrowserClient)commandWithTimeout(ctx context.Context,method string,params any,sessionID string,result any,timeout time.Duration)error{c.mu.Lock();defer c.mu.Unlock();if c.pipeMode{return c.pipeCommandLocked(ctx,method,params,sessionID,result,timeout)};if c.conn==nil{return errors.New("browser is unavailable")};c.seq++;id:=c.seq;message:=map[string]any{"id":id,"method":method,"params":params};if sessionID!=""{message["sessionId"]=sessionID};if err:=c.conn.WriteJSON(message);err!=nil{return err};if timeout<=0{timeout=10*time.Second};_=c.conn.SetReadDeadline(time.Now().Add(timeout));defer c.conn.SetReadDeadline(time.Time{});for{_,data,err:=c.conn.ReadMessage();if err!=nil{return err};var envelope struct{ID int64 `json:"id"`;Result json.RawMessage `json:"result"`;Error *struct{Code int `json:"code"`;Message string `json:"message"`} `json:"error"`};if err:=json.Unmarshal(data,&envelope);err!=nil{continue};if envelope.ID!=id{continue};if envelope.Error!=nil{return fmt.Errorf("cdp %d: %s",envelope.Error.Code,envelope.Error.Message)};if result!=nil&&len(envelope.Result)>0{return json.Unmarshal(envelope.Result,result)};return nil}}
func(c *BrowserClient)inPipeMode()bool{c.mu.Lock();defer c.mu.Unlock();return c.pipeMode}
func(c *BrowserClient)isBiDi()bool{c.mu.Lock();defer c.mu.Unlock();return c.firefoxBiDi}
func(c *BrowserClient)bidiCommand(ctx context.Context,method string,params any,result any)error{c.mu.Lock();defer c.mu.Unlock();if c.conn==nil{return errors.New("browser is unavailable")};c.seq++;id:=c.seq;message:=map[string]any{"id":id,"method":method,"params":params};_ = c.conn.SetWriteDeadline(time.Now().Add(20*time.Second));writeErr:=c.conn.WriteJSON(message);_ = c.conn.SetWriteDeadline(time.Time{});if writeErr!=nil{if c.bidiEndpoint!=""{if recon,_,dialErr:=websocket.DefaultDialer.DialContext(ctx,c.bidiEndpoint,nil);dialErr==nil{_=c.conn.Close();c.conn=recon;_ = c.conn.SetWriteDeadline(time.Now().Add(20*time.Second));writeErr=c.conn.WriteJSON(message);_ = c.conn.SetWriteDeadline(time.Time{})}};if writeErr!=nil{return writeErr}};timeout:=c.cfg.ActionTimeout;if timeout<=0{timeout=10*time.Second};_=c.conn.SetReadDeadline(time.Now().Add(timeout));defer c.conn.SetReadDeadline(time.Time{});for{_,data,err:=c.conn.ReadMessage();if err!=nil{return err};var env struct{ID *int64 `json:"id"`;Type string `json:"type"`;Result json.RawMessage `json:"result"`;Error json.RawMessage `json:"error"`;Message string `json:"message"`};if err:=json.Unmarshal(data,&env);err!=nil{continue};if env.ID==nil||*env.ID!=id{continue};if len(env.Error)>0&&string(env.Error)!="null"{var obj struct{Code int `json:"code"`;Message string `json:"message"`};if err:=json.Unmarshal(env.Error,&obj);err==nil&&(obj.Code!=0||obj.Message!=""){return fmt.Errorf("bidi %d: %s",obj.Code,obj.Message)};var s string;if err:=json.Unmarshal(env.Error,&s);err==nil&&s!=""{if env.Message!=""{return fmt.Errorf("bidi %s: %s",s,env.Message)};return fmt.Errorf("bidi %s",s)};return fmt.Errorf("bidi error: %s",string(env.Error))};if env.Type=="error"{if env.Message!=""{return fmt.Errorf("bidi error: %s",env.Message)};return fmt.Errorf("bidi error")};if result!=nil&&len(env.Result)>0{return json.Unmarshal(env.Result,result)};return nil}}
func bidiFindKey(v any,key string)(string,bool){switch t:=v.(type){case map[string]any:for k,val:=range t{if k==key{if s,ok:=val.(string);ok{return s,true}};if s,ok:=bidiFindKey(val,key);ok{return s,true}};case []any:for _,e:=range t{if s,ok:=bidiFindKey(e,key);ok{return s,true}}};return "",false}
func(c *BrowserClient)bidiPageMetadata(ctx context.Context,s *browserSession)(pageMetadataResult,error){var raw map[string]any;if err:=c.bidiCommand(ctx,"script.evaluate",map[string]any{"expression":"({url:location.href,title:document.title})","target":map[string]any{"context":s.TargetID},"awaitPromise":false},&raw);err!=nil{return pageMetadataResult{},err};url,_:=bidiFindKey(raw,"url");title,_:=bidiFindKey(raw,"title");return pageMetadataResult{URL:url,Title:title},nil}
func(c *BrowserClient)bidiOpen(ctx context.Context,sessionID string,out any)error{if strings.TrimSpace(sessionID)==""{return errors.New("session_id is required")};c.stateMu.Lock();s:=c.sessions[sessionID];c.stateMu.Unlock();if s!=nil{meta,_:=c.bidiPageMetadata(ctx,s);return jsonInto(out,map[string]any{"session_id":sessionID,"context_id":sessionID,"page_id":s.TargetID,"url":meta.URL,"title":meta.Title})};var created struct{Context string `json:"context"`};if err:=c.bidiCommand(ctx,"browsingContext.create",map[string]any{"type":"tab"},&created);err!=nil{return err};if created.Context==""{return errors.New("bidi browsingContext.create missing context")};c.stateMu.Lock();c.sessions[sessionID]=&browserSession{TargetID:created.Context,Refs:make(map[string]browserRef),LastUsed:time.Now()};c.stateMu.Unlock();return jsonInto(out,map[string]any{"session_id":sessionID,"context_id":sessionID,"page_id":created.Context,"url":"about:blank","title":""})}
func(c *BrowserClient)bidiCloseSession(ctx context.Context,sessionID string,out any)error{c.stateMu.Lock();s:=c.sessions[sessionID];c.stateMu.Unlock();if s==nil{return jsonInto(out,map[string]any{"closed":false})};_ = c.bidiCommand(ctx,"browsingContext.close",map[string]any{"context":s.TargetID},nil);c.stateMu.Lock();delete(c.sessions,sessionID);c.stateMu.Unlock();return jsonInto(out,map[string]any{"closed":true})}
func(c *BrowserClient)bidiNavigate(ctx context.Context,sessionID,url string,out any)error{s,err:=c.getSession(sessionID);if err!=nil{return err};if url==""{return errors.New("url is required")};var nav map[string]any;_ = c.bidiCommand(ctx,"browsingContext.navigate",map[string]any{"context":s.TargetID,"url":url,"wait":"complete"},&nav);time.Sleep(150*time.Millisecond);meta,_:=c.bidiPageMetadata(ctx,s);if meta.URL==""{meta.URL=url};c.touch(s);return jsonInto(out,map[string]any{"page_id":s.TargetID,"url":meta.URL,"title":meta.Title,"status":200})}
func(c *BrowserClient)bidiSnapshot(ctx context.Context,sessionID string,out any)error{s,err:=c.getSession(sessionID);if err!=nil{return err};var raw map[string]any;if err:=c.bidiCommand(ctx,"script.evaluate",map[string]any{"expression":"document.body?document.body.innerText:''","target":map[string]any{"context":s.TargetID},"awaitPromise":false},&raw);err!=nil{return err};text,_:=bidiFindKey(raw,"value");meta,_:=c.bidiPageMetadata(ctx,s);c.stateMu.Lock();s.Refs=make(map[string]browserRef);s.LastUsed=time.Now();c.stateMu.Unlock();snap:=text;if len(snap)>4000{snap=snap[:4000]};return jsonInto(out,map[string]any{"page_id":s.TargetID,"url":meta.URL,"title":meta.Title,"snapshot":snap})}
func browserDisplayEnv(display string)[]string{if strings.TrimSpace(display)==""{return nil};env:=os.Environ();out:=make([]string,0,len(env)+1);for _,kv:=range env{if !strings.HasPrefix(kv,"DISPLAY="){out=append(out,kv)}};return append(out,"DISPLAY="+strings.TrimSpace(display))}
func isFirefox(binary, preference string) bool { if strings.EqualFold(strings.TrimSpace(preference), "firefox") { return true }; base := strings.ToLower(filepath.Base(binary)); return strings.Contains(base, "firefox") }
func findBrowser(preference string)(string,error){for _,name:=range browserCandidates(preference){if path,err:=exec.LookPath(name);err==nil{return path,nil}};for _,path:=range browserAbsoluteCandidates(preference){if _,err:=os.Stat(path);err==nil{return path,nil}};return "",fmt.Errorf("no supported browser installed; looked for Chrome, Chromium, Edge, or Firefox")}
func browserCandidates(preference string)[]string{switch strings.ToLower(preference){case"chrome":return []string{"google-chrome","google-chrome-stable","chrome"};case"chromium":return []string{"chromium","chromium-browser"};case"edge":return []string{"microsoft-edge","microsoft-edge-stable","msedge"};case"firefox":return []string{"firefox","firefox-esr"};default:return []string{"firefox","firefox-esr","google-chrome","google-chrome-stable","chromium","chromium-browser","microsoft-edge","microsoft-edge-stable","msedge"}}}
func browserAbsoluteCandidates(preference string)[]string{all:=browserCandidates(preference);if runtime.GOOS=="darwin"{return append(all,"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome","/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge","/Applications/Chromium.app/Contents/MacOS/Chromium")};if runtime.GOOS=="windows"{return append(all,`C:\Program Files\Google\Chrome\Application\chrome.exe`,`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`,`C:\Program Files\Microsoft\Edge\Application\msedge.exe`)};return append(all,"/usr/bin/firefox","/usr/bin/firefox-esr","/usr/bin/google-chrome","/usr/bin/google-chrome-stable","/usr/bin/chromium","/usr/bin/chromium-browser","/usr/bin/microsoft-edge","/usr/bin/microsoft-edge-stable")}
func marshalInto(value any,out any)error{data,err:=json.Marshal(value);if err!=nil{return err};return json.Unmarshal(data,out)}
func jsonInto(out any,value any)error{if out==nil{return nil};data,err:=json.Marshal(value);if err!=nil{return err};return json.Unmarshal(data,out)}
